/*!
 * verb-helper-codelinks <https://github.com/jonschlinkert/verb-helper-codelinks>
 *
 * Copyright (c) 2015, Jon Schlinkert.
 * Licensed under the MIT License.
 */

'use strict';

var api = require('api-toc');

/**
 * Generate a clickable list of API "code-links" for the methods in directory.
 * Each link takes you to the beginning line of code for the corresponding method.
 *
 * Usage:
 *
 * ```js
 * {%= apitoc('lib/') %}
 * ```
 */

module.exports = function(dir, append) {
  var res = api(dir, append);
  res += '\n';
  res += '\n';
  res += '_(Code links generated by Verb\'s [api-toc] helper)_';
  res += '\n';
  res += '[api-toc]: https://github.com/jonschlinkert/api-toc'
  return res;
};
